# Generated by Django 3.1.3 on 2021-01-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='licensePlate',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.photo'),
        ),
    ]
