# Generated by Django 3.1.3 on 2021-01-11 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210109_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='atuador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.sensor'),
        ),
    ]
