# Generated by Django 3.1.3 on 2021-01-17 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210111_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
