# Generated by Django 3.1.3 on 2021-01-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_sensor_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='atuador',
            new_name='actuator',
        ),
    ]
