# Generated by Django 3.1.3 on 2021-01-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210117_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensortype',
            field=models.CharField(choices=[('led', 'LED'), ('plug', 'PLUG'), ('camera', 'CAMERA'), ('servo', 'SERVO'), ('motion', 'MOTION'), ('temperature', 'TEMPERATURE'), ('luminosity', 'LUMINOSITY')], default='Undefined', max_length=20),
        ),
    ]
