# Generated by Django 3.1.3 on 2021-01-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20210120_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='lux_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='temp_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
