# Generated by Django 3.1.3 on 2021-01-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20210121_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='lux_max',
            new_name='lux_lim',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='temp_max',
            new_name='temp_lim',
        ),
    ]
