# Generated by Django 3.1.3 on 2021-01-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20210121_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='lux_lim',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
