# Generated by Django 3.1.3 on 2021-01-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20210122_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='lux_lim',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
