# Generated by Django 3.1.3 on 2021-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20210122_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
