# Generated by Django 3.1.3 on 2021-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20210122_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='auto',
            field=models.BooleanField(default=True),
        ),
    ]
