# Generated by Django 3.1.3 on 2021-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_sensor_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/profile'),
        ),
    ]
