# Generated by Django 3.1.3 on 2021-02-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_housekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housekey',
            name='Key',
        ),
        migrations.AddField(
            model_name='housekey',
            name='key',
            field=models.CharField(blank=True, default='2036412329', editable=False, max_length=10, unique=True),
        ),
    ]
