# Generated by Django 3.1.3 on 2021-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20210203_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='housekey',
            name='key',
            field=models.CharField(blank=True, default='9012155589', editable=False, max_length=10, unique=True),
        ),
    ]
