# Generated by Django 3.1.3 on 2021-02-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20210203_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekey',
            name='key',
            field=models.CharField(blank=True, default='3360040622', editable=False, max_length=10, unique=True),
        ),
    ]
