# Generated by Django 3.1.3 on 2021-02-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20210203_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekey',
            name='key',
            field=models.CharField(blank=True, default='4610053198', editable=False, max_length=10, unique=True),
        ),
    ]
