# Generated by Django 3.1.3 on 2021-02-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_auto_20210203_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='key',
        ),
        migrations.AlterField(
            model_name='housekey',
            name='key',
            field=models.CharField(blank=True, default='5230395177', editable=False, max_length=10, unique=True),
        ),
    ]
