# Generated by Django 3.1.3 on 2021-02-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_auto_20210203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='key',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='housekey',
            name='key',
            field=models.CharField(blank=True, default='3428113285', editable=False, max_length=10, unique=True),
        ),
    ]
