# Generated by Django 3.1.3 on 2021-02-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20210203_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekey',
            name='key',
            field=models.CharField(blank=True, default='1971419443', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
    ]
